name: lan_code
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  shared_preferences: ^2.0.9
  mask_text_input_formatter: ^2.0.0
  url_launcher: ^6.0.17
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_svg: 0.20.0-nullsafety.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - image/icon/password.svg
    - image/icon/email.svg
    - image/icon/hide.svg
    - image/icon/show.svg
    - image/icon/vk.svg
    - image/icon/okru.svg
    - image/icon/facebook.svg
    - image/icon/google.svg
    - image/icon/twitter.svg
    - image/icon/person.svg
    - image/performance/One.png
    - image/performance/Two.png
    - image/performance/Three.png
    - image/performance/Four.png
    - image/icon/arrow.svg
    - image/icon/favorite.svg
    - image/icon/arrowBottom.svg
    - image/icon/reverse.svg
    - image/icon/handbook.svg
    - image/icon/date.svg
    - image/icon/location.svg
    - image/icon/ruble.svg
    - image/backCity.png
    - image/icon/magnifier.svg
    - image/defoult/defoultUser.jpg
    - image/icon/tickets.svg
    - image/icon/settings.svg
    - image/icon/exit.svg
    - image/icon/myExcursion.svg
    - image/icon/phone.svg
    - image/icon/add.svg
    - image/icon/time.svg


      #data
    - image/data/city/сочи.png
    - image/data/city/анапа.png
    - image/data/city/москва.jpg
    - image/data/city/тюмень.jpeg
    - image/data/user/иван.jpg
    - image/data/user/анна.jpg
    - image/data/user/мария.jpg
    - image/data/user/миша.jpg
    - image/data/excursion/сочи1.jpg
    - image/data/excursion/сочи2.jpg
    - image/data/excursion/анапа1.jpg
    - image/data/excursion/москва1.jpg
    - image/data/excursion/москва2.jpg
    - image/data/excursion/москва3.jpg
    - image/data/excursion/тюмень1.jpg
    - image/data/excursion/тюмень2.jpg
    - image/data/excursion/сочи11.jpg
    - image/data/excursion/сочи12.png
    - image/data/excursion/сочи13.jpg
    - image/data/excursion/сочи21.jpg
    - image/data/excursion/сочи22.jpg
    - image/data/excursion/анапа11.jpg
    - image/data/excursion/анапа12.jpg
    - image/data/excursion/анапа13.jpg
    - image/data/excursion/москва11.jpg
    - image/data/excursion/москва12.jpg
    - image/data/excursion/москва21.jpg
    - image/data/excursion/москва31.jpg
    - image/data/excursion/москва32.jpg
    - image/data/excursion/тюмень21.jpg
    - image/data/excursion/тюмень22.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 900
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Light.ttf
          weight: 200

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
